import './globals.sass';

import type { Metadata } from 'next';
import { Onest } from 'next/font/google';

const onest = Onest({
  variable: '--font-onest',
  subsets: ['cyrillic', 'latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable}`}>{children}</body>
    </html>
  );
}
